version: '3'
services:
  db2:
    image: mysql:8.0.17
    restart: unless-stopped
    environment:
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpassword'
      MYSQL_ROOT_PASSWORD: 'secretPasswordNotRealForNow' # do not change, it is used by the checker.
      MYSQL_DATABASE: 'vulnapp' 
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  unical2:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - "db2"
    ports:
      - '5000:5000'
      - '8025:8025'
      - '2222:22'

volumes:
  db_data:

  
