version: "2.4"

services:
  nginx-app: # nginx for static files
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html/:ro
    ports:
      - "8000:80"
      - "8081:81"

  php-app: # php application
    build: ./
    image: ilbonus-php-app
    environment:
      - "APPNAME=ILBONUS"
    volumes:
      - ./index.php:/var/www/html/index.php:ro
      - ./includes:/var/www/html/includes:ro
      - ./templates:/var/www/html/templates:ro
      - ./extensions:/var/www/html/extensions:ro
      - ./logs:/var/www/html/logs
      - ./uploads:/var/www/html/uploads
      - ./flagIds.php:/var/www/html/flagIds.php:ro
    read_only: true
    tmpfs:
      - /tmp/
      
  mongo-app: # mongo database for the application
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ilbonus
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      
